title: 'asdfa/..₺aaa:){{191*7}}'
description: 'asdfa/..₺aaa:){{191*7}}'
template:
  repo: 'asdfa..aaa:)191*7-template'
  name: 'asdfa..aaa:)191*7'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
